### ISSUE TITLE
Question about FlexFlow Feature

### ISSUE THREAD

**Issue by alantq** [mlcommons/chakra#120]
> Please provide a detailed description of your question or the information you seek.
Hi,

I noticed that the FlexFlow support feature was deprecated in the past commit with no comment. I am wondering can I have some detail about this feature? Is it under actively development or is there any bug or error in this feature?

Thank you so much!

**Comment by srinivas212** [comment]
The feature was deprecated due to lack of users and lack of developers to maintain it.
