### ISSUE TITLE
Error when using chakra_converter

### ISSUE THREAD

**Issue by sriraman2020** [mlcommons/chakra#127]
## Describe the Bug
chakra/src/converter/pytorch_node.py", line 89, in parse_data
    raise ValueError(
ValueError: Unsupported schema version '1.0.1'. Please check if the schema version is in the list of supported versions: ['1.0.2-chakra.0.0.4', '1.0.3-chakra.0.0.4', '1.1.0-chakra.0.0.4']

Error seen with chakra_converter. Any suggestions.

## Steps to Reproduce
> Steps to reproduce the behavior.
> Please include the version information where the bug was observed.

## Expected Behavior
> A clear and concise description of what you expected to happen.

## Screenshots
> If applicable, add screenshots to help explain your problem.

**Comment by rafsalas19** [comment]
I have also run into this issue. I installed chakra using this method:
```
# Install latest from github
$ pip install https://github.com/mlcommons/chakra/archive/refs/heads/main.zip
```

**Comment by sriraman2020** [comment]
With  PyTorch version 2.1.2. the issue is not seen. Issue can be closed.

**Comment by 191220042** [comment]
> With PyTorch version 2.1.2. the issue is not seen. Issue can be closed.使用 PyTorch 版本 2.1.2 时未发现该问题。可以关闭该问题。
我在使用pytorch2.1.2时也会出现这个问题

**Comment by 191220042** [comment]
> I have also run into this issue. I installed chakra using this method:我也遇到了这个问题。我使用这种方法安装了 Chakra：
> 
> ```
> # Install latest from github
> $ pip install https://github.com/mlcommons/chakra/archive/refs/heads/main.zip
> ```

hello,is this problem solved?
