### ISSUE TITLE
May I ask how to obtain PyTorch execution graph?

### ISSUE THREAD

**Issue by bluegrey23** [mlcommons/chakra#28]
I can't find the information about PyTorch Execution Graph, although I programed on pytorch. could you give me some advice about it , so as to feed chakra to run.

**Comment by TaekyungHeo** [comment]
@bluegrey23, you can use ExecutionTraceObserver to collect execution traces, as shown in this example: https://github.com/facebookresearch/param/blob/40ffa8fb4a2ae0ae923eaecd3c098bb6f60c15d0/train/compute/python/pytorch/run_benchmark.py#L302.

**Comment by TaekyungHeo** [comment]
The following command sequence worked for me to collect execution traces in PARAM.
```
$ conda create -n pytorch-trace python=3.9.0
$ conda activate pytorch-trace
$ conda install cudatoolkit=11.7 -c conda-forge
$ conda install pytorch pytorch-cuda=11.7 -c pytorch -c nvidia
$ conda install numpy
$ git clone --recurse-submodules git@github.com:facebookresearch/param.git
$ cd param/train/compute/python
$ python setup.py install
$ python -m param_bench.train.compute.python.pytorch.run_benchmark\
    -c examples/pytorch/configs/alex_net.json\
    -d cuda\
    --eg\
    --cuda-l2-cache on
```
