### ISSUE TITLE
Do you have a plan for integrating chakra to SST?

### ISSUE THREAD

**Issue by jimmylegendary** [mlcommons/chakra#29]
If you have the plan, I would like to know.
Or, if you want to integrate chakra to SST, but it is not yet prioritized, I am willing to contribute this and discuss about it.

**Comment by TaekyungHeo** [comment]
Thank you for your interest in Chakra. What exactly do you mean by "integration with SST"? Are you looking to incorporate et_feeder as a component of SST, or are you considering adding other components to SST? To my knowledge, there isn't currently a plan to support SST integration. Nevertheless, we definitely welcome your contributions :)

**Comment by jimmylegendary** [comment]
yes right. There are many add-on and different type of input format, so I was wondering how to use chakra in SST.
As I know key point of chakra for now is chakra schema, am I understanding right?

**Comment by srinivas212** [comment]
Closing issue.
