### ISSUE TITLE
Would it be possible to provide an example of input files?

### ISSUE THREAD

**Issue by tangyuelm** [mlcommons/chakra#33]
Dear Authors,

Thank you for the tool. I am new to Charka and want to use the performance model for my current project. I have just started installing the tool and generating the execution trace. I see the following instruction for converting ET from Pytorch but I have no idea what the input file, output file, default simulated run time, and num dims look like. Would it be possible to provide an example of these files or configurations? Thank you.
$ python -m et_converter.et_converter\
    --input_type PyTorch\
    --input_filename <input_filename>\
    --output_filename <output_filename>\
    --default_simulated_run_time <default_simulated_run_time>\
    --num_dims <num_dims>

**Comment by TaekyungHeo** [comment]
Please take a look at this issue to see how to generate PyTorch execution traces: https://github.com/mlcommons/chakra/issues/28

The ASTRA-sim README file may help you understand how the toolchains work: https://github.com/astra-sim/astra-sim

You can find an example PyTorch execution trace here: https://github.com/facebookresearch/param/tree/main/train/compute/python/test/data

Let me see if we can add some to this repository. Currently, we don't have any.

**Comment by tangyuelm** [comment]
Thank you for the suggestions. I am working on the ASTRA-sim but found some errors during the installation. https://github.com/astra-sim/astra-sim/issues/93
I am wondering if there are some requirements for the operation system and conda environment for Chakra and ASTRA-sim. Currently, I use Ubuntu 18.04 (both wsl and a Linux system installed desktop failed). The detailed environment is as follows.
![image](https://github.com/mlcommons/chakra/assets/58452529/ffcb815d-861f-4908-a800-1cdc7acbbebe)

**Comment by srinivas212** [comment]
Closing this issue. See - https://github.com/astra-sim/astra-sim/issues/93.
