### ISSUE TITLE
lack of attribute  'parent'

### ISSUE THREAD

**Issue by LinHanyueEsar** [mlcommons/chakra#40]
when I was using AstraSim-2.0 to generate chakra traces from 1.0, using the following command:
python3 -m chakra.et_converter.et_converter \
    --input_type Text \
    --input_filename ../../../inputs/workload/ASTRA-sim-1.0/Resnet50_DataParallel.txt \
    --output_filename ../../../inputs/workload/ASTRA-sim-2.0/Resnet50_DataParallel \
    --num_npus 64 \
    --num_dims 1 \
    --num_passes 1
I met a bug:
DEBUG [04/17/2024 12:04:48 PM] Traceback (most recent call last):
  File "/home/esar/.local/lib/python3.10/site-packages/chakra/et_converter/et_converter.py", line 106, in main
    converter.convert()
  File "/home/esar/.local/lib/python3.10/site-packages/chakra/et_converter/text2chakra_converter.py", line 147, in convert
    self.convert_data_parallel(f, num_layers)
  File "/home/esar/.local/lib/python3.10/site-packages/chakra/et_converter/text2chakra_converter.py", line 202, in convert_data_parallel
    self.add_parent(fwd_comp_node, layers[idx-1].fwd_comp_node)
  File "/home/esar/.local/lib/python3.10/site-packages/chakra/et_converter/text2chakra_converter.py", line 136, in add_parent
    child_node.parent.append(parent_node.id)
AttributeError: parent
So I check the Node file in ./et_def/et_def.proto and find that the node don't have attribute 'parent', I add at the bottom like:
  //parent
  repeated uint64 parent=11;
and later it passes.

**Comment by TaekyungHeo** [comment]
The trace_link and et_converter have been updated by the following PRs. First, please use the updated tools:
* https://github.com/mlcommons/chakra/pull/47
* https://github.com/mlcommons/chakra/pull/50
Second, ensure you use PyTorch nightly for some time to collect traces, as we are utilizing the latest features from the PyTorch profiler to properly correlate traces.

**Comment by srinivas212** [comment]
Closing the issue. Pl reopen if you have issue w/ latest code.
