### ISSUE TITLE
record_param_comms

### ISSUE THREAD

**Issue by XcodeRole** [mlcommons/chakra#51]
I have encountered numerous 'record_param_comms' nodes in Chakra ET, which serve as child nodes to collective communication nodes. I presume that these functions are intended to log communication information, such as the communication domain for collective communications, the counterpart in point-to-point communications, the size of the communication volume, and other parameters. However, this is just my speculation, as I have not been able to find specific invocations of these functions within PyTorch. How is this information utilized within Chakra?

**Comment by TaekyungHeo** [comment]
As you have mentioned, record_param_comms functions as a parent node of a collective communication node. In Chakra, we do not use record_param_comms directly. We can easily identify communication nodes with record_param_comms. Moreover, it serves as a bridge between the actual collective communication node and its parent. We plan to remove record_param_comms from traces by updating the PyTorch profiler.

**Comment by srinivas212** [comment]
Thanks for reporting this issue. We can review and accept a PR if you would like to add this feature to et converter.
