### ISSUE TITLE
what is the expected way to collect pytorch execution trace?

### ISSUE THREAD

**Issue by chenqianfzh** [mlcommons/chakra#52]
wonder whether you can show how to get the pytorch execution trace output that Chakra will take and convert?

I tried to collect the trace using the default trace handler, torch.profiler.tensorboard_trace_handler, and the torch.jit.trace(). The outputs from both trials are very different from what pytorch2chakra_converter would expect.

Thanks.

**Comment by TaekyungHeo** [comment]
Hi @chenqianfzh,

Thank you for reaching out. While there is a converter from PyTorch execution traces to Chakra execution traces in Chakra (et_converter), it was previously incomplete.

To address this, changes have been made across three repositories: PARAM, Chakra, and ASTRA-sim:
* In PARAM, the trace_link.py tool is designed to merge PyTorch execution traces (covering CPU operators) with Kineto traces (focused on GPU operators), resulting in a unified execution file ([View changes here](https://github.com/TaekyungHeo/param/tree/PR-PyTorch-ET-simulation))
* The PyTorch ET to Chakra ET converter has received significant enhancements, allowing it to seamlessly bridge and differentiate between GPU and CPU operations ([View changes here](https://github.com/TaekyungHeo/chakra-1/tree/PR-PyTorch-ET-simulation))
* Additionally, ASTRA-sim has been updated to better distinguish between CPU and GPU operations ([View changes here](https://github.com/astra-sim/astra-sim/tree/PR-PyTorch-ET-simulation))

We will merge these changes once we confirm they work as expected.

For the next steps, you'll need to collect both the PyTorch execution traces and Kineto execution traces during the model's execution. Once gathered, use trace_link.py to combine the PyTorch ET with the Kineto ET. This merged trace can then be fed into the converter to produce a simulation-compatible Chakra execution trace. Please refer to the attached figure for clarification:

<img width="1319" alt="Screenshot 2023-10-23 at 9 14 07 AM" src="https://github.com/mlcommons/chakra/assets/7621438/7227797b-1e19-4492-ae8f-ec787f255f0c">

Lastly, Saeed from HP labs has shared some files to demonstrate the collection of PyTorch execution traces and Kineto traces. I recommend checking them out: [examples.tgz](https://github.com/mlcommons/chakra/files/13070754/examples.tgz)

**Comment by srinivas212** [comment]
Does this help answer your question, @chenqianfzh ?
