### ISSUE TITLE
import error in pytorch2chakra_converter.py

### ISSUE THREAD

**Issue by francisgan** [mlcommons/chakra#56]
Runing pytorch2chakra_converter.py file causes this error, where BOOL, FLOAT, ..., STRINGS can't be imported from chakra/et_def/et_def_pb2.py

<img width="922" alt="Screenshot 2023-11-06 at 18 34 47" src="https://github.com/mlcommons/chakra/assets/102556156/20b33676-4fe4-428d-936a-9f63ac0a8e89">

**Comment by TaekyungHeo** [comment]
@francisgan, Thank you for reporting this issue with pytorch2chakra_converter.py. It appears that the problem stems from outdated definitions in the tool, which do not align with the recent updates to the Chakra schema. We are aware of this, and there is a pull request (PR) in the pipeline that addresses these import errors. Please keep an eye on the project's PRs for the update. We appreciate your patience and understanding as we work to resolve this.

**Comment by TaekyungHeo** [comment]
Please take a look at the PR https://github.com/mlcommons/chakra/pull/58/
