### ISSUE TITLE
How to distinguish communication domains between different communication (ET) node？

### ISSUE THREAD

**Issue by XcodeRole** [mlcommons/chakra#71]
Regarding astra’s issue: https://github.com/astra-sim/astra-sim/issues/195, I think different parallel groups should be defined in comm_group_configuration, corresponding to tensor parallel, data parallel, etc. But this Chakra support is required. Currently, chakra cannot distinguish the communication domains to which communication nodes in ET belong.
So is there any way to correspond the communication nodes in chakra ET to different communication domains?

**Comment by TaekyungHeo** [comment]
While ASTRA-sim is a reference implementation of our downstream tools and a simulator, we are not officially supporting ASTRA-sim, nor are we tracking all ASTRA-sim issues and PRs.

Currently, communicator groups are collected in PyTorch. The Chakra schema and the postprocessors have not yet been updated to encode them properly in the final Chakra traces for simulation. We will get there soon.

**Comment by XcodeRole** [comment]
Thank you for your response. I will try to address the issue according to the suggestions in the [PR](https://github.com/pytorch/pytorch/pull/126317).
