### ISSUE TITLE
the Converted Text file can't be visualized by et_visualizer

### ISSUE THREAD

**Issue by lulala-s** [mlcommons/chakra#76]
## Describe the Bug
> mistake report is the following thing
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/chakra/et_visualizer/et_visualizer.py", line 81, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/chakra/et_visualizer/et_visualizer.py", line 40, in main
    while decode_message(et, node):
  File "/usr/local/lib/python3.8/dist-packages/chakra/third_party/utils/protolib.py", line 138, in decodeMessage
    message.ParseFromString(buf)
google.protobuf.message.DecodeError: Error parsing message
```
the command which I used to visualizer is this
```
python3 -m chakra.et_visualizer.et_visualizer\
    --input_filename ../../outputs/convert_result/Resnet50_DataParallel/Resnet50_DataParallel.0.et\
    --output_filename ../../outputs/pic_result/Resnet50.pdf
```

## Steps to Reproduce
 I use the following command to convert the txt to et file
```
python3 -m chakra.et_converter.et_converter\
    --input_type Text\
    --input_filename ../../inputs/workload/ASTRA-sim-1.0/MLP_ModelParallel.txt\
    --output_filename ../../outputs/convert_result/MLP_ModelParallel\
    --num_npus 64\
    --num_dims 1\
    --num_passes 1
```
and the result is like this 
```
�
schema�1.0.2-chakra.0.0.4�

input_file��MODEL											
6											
layer_64_1_mlp0	-1	32291	ALLGATHER	37632	32291	ALLREDUCE	37632	12864	NONE	0	3229
layer_64_1_mlp1	-1	7488	ALLGATHER	65536	7488	ALLREDUCE	65536	3648	NONE	0	749
layer_64_1_mlp2	-1	7488	ALLGATHER	65536	7488	ALLREDUCE	65536	3456	NONE	0	749
layer_64_1_mlp3	-1	14144	ALLGATHER	147456	14144	ALLREDUCE	147456	10368	NONE	0	1414
layer_64_1_mlp4	-1	7488	ALLGATHER	65536	7488	ALLREDUCE	65536	3648	NONE	0	749
layer_64_2_mlp5	-1	9984	ALLGATHER	65536	9984	ALLREDUCE	65536	3456	NONE	0	998%COMP_NODE_layer_64_1_mlp0_FWD8��Q(COMM_COLL_NODE_layer_64_1_mlp0_ALLGATHER*
```

## Expected Behavior
Maybe is the convert file has some problems?

**Comment by TaekyungHeo** [comment]
Could you please share the input files as a .tgz archive so that we can reproduce and fix the issue?

**Comment by lulala-s** [comment]
[ASTRA-sim-1.0.zip](https://github.com/user-attachments/files/15781416/ASTRA-sim-1.0.zip)
[Uploading convert_result.zip…]()

**Comment by lulala-s** [comment]
[ASTRA-sim-1.0.zip](https://github.com/user-attachments/files/15781423/ASTRA-sim-1.0.zip)
[convert_result.zip](https://github.com/user-attachments/files/15781424/convert_result.zip)

**Comment by lulala-s** [comment]
the first is the astra_sim‘s input ,the second stores some result by et_converter

**Comment by srinivas212** [comment]
We do have resources to actively support text converter. You could request help from ASTRA-sim devs.

**Comment by tninth** [comment]
> ## 描述 Bug
> > 错误报告是以下内容
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.8/dist-packages/chakra/et_visualizer/et_visualizer.py", line 81, in <module>
>     main()
>   File "/usr/local/lib/python3.8/dist-packages/chakra/et_visualizer/et_visualizer.py", line 40, in main
>     while decode_message(et, node):
>   File "/usr/local/lib/python3.8/dist-packages/chakra/third_party/utils/protolib.py", line 138, in decodeMessage
>     message.ParseFromString(buf)
> google.protobuf.message.DecodeError: Error parsing message
> ```
> 
> 用于可视化器的命令是这个
> 
> ```
> python3 -m chakra.et_visualizer.et_visualizer\
>     --input_filename ../../outputs/convert_result/Resnet50_DataParallel/Resnet50_DataParallel.0.et\
>     --output_filename ../../outputs/pic_result/Resnet50.pdf
> ```
> 
> ## 重现步骤
> 我使用以下命令将 txt 转换为 et 文件
> 
> ```
> python3 -m chakra.et_converter.et_converter\
>     --input_type Text\
>     --input_filename ../../inputs/workload/ASTRA-sim-1.0/MLP_ModelParallel.txt\
>     --output_filename ../../outputs/convert_result/MLP_ModelParallel\
>     --num_npus 64\
>     --num_dims 1\
>     --num_passes 1
> ```
> 
> 结果是这样的
> 
> ```
> ����
> �schema���1.0.2-chakra.0.0.4���
> 
> input_file����MODEL											
> 6											
> layer_64_1_mlp0	-1	32291	ALLGATHER	37632	32291	ALLREDUCE	37632	12864	NONE	0	3229
> layer_64_1_mlp1	-1	7488	ALLGATHER	65536	7488	ALLREDUCE	65536	3648	NONE	0	749
> layer_64_1_mlp2	-1	7488	ALLGATHER	65536	7488	ALLREDUCE	65536	3456	NONE	0	749
> layer_64_1_mlp3	-1	14144	ALLGATHER	147456	14144	ALLREDUCE	147456	10368	NONE	0	1414
> layer_64_1_mlp4	-1	7488	ALLGATHER	65536	7488	ALLREDUCE	65536	3648	NONE	0	749
> layer_64_2_mlp5	-1	9984	ALLGATHER	65536	9984	ALLREDUCE	65536	3456	NONE	0	998%��COMP_NODE_layer_64_1_mlp0_FWD��8���Q���(COMM_COLL_NODE_layer_64_1_mlp0_ALLGATHER��*�
> ```
> 
> ## 预期行为
> 也许转换文件有一些问题？

Hello, I encountered a similar problem, can you solve it successfully?
